# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a164b1dfceaf57ac378c6a460da5fb0de6e491b5b699479063cbab411e1ca50df6711672a7cb8fa16565b7f0296d256082a05a5eaee30b7e8a22621ce57c8b74

test:
  secret_key_base: 6679d72e5146cf9170acb283fafc60f447ebddb86d9d838d95a297cdf110fda2d63befb87950f2948847012bf0218ce1cce8013d125ffd6597b797f98d46e31b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
